### ISSUE TITLE
Interpolation bug with threaded batch interpolation

### ISSUE THREAD

**Issue by tangtang95** [julianxhokaxhiu/CaitSith#1]
The .cam files batch interpolated using a intel cpu vs amd cpu provides different results. Tested with the interpolated moviecam.lgp using a hash algorithm and the result were different. From ingame it seems the correct one is the one produced by AMD cpu

**Comment by julianxhokaxhiu** [comment]
Interesting bug. I might need to check compilation flags and maybe port the whole project to .NET 6.0. I'll look into this, thanks!

**Comment by julianxhokaxhiu** [comment]
I forgot to mention I did bump this project to .NET 7. Would you be able to retry and let me know if the bug has been fixed? Thanks!

**Comment by tangtang95** [comment]
It doesn't seem to happen anymore. Actually I do not remember how it was different, but maybe I used a bugged LGP tool creation that introduce some bug.

Anyway I cannot reproduce it anymore, so I think you can close it.

**Comment by julianxhokaxhiu** [comment]
Thanks!
